#A prodlike environment that is identical to PROD except that it accesses a different database

name: imghub-dev

services:

  imghub-dev-database:
    container_name: imghub-dev-database
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imghub-dev

  imghub-dev-pgadmin:
    container_name: imghub-dev-pgadmin
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - imghub-dev-database

  imghub-api:
    container_name: imghub-api
    image: imghub-api:dev
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "80:8080"
    depends_on:
      - imghub-dev-database
