name: imghub-prod

services:

  imghub-prod-database:
    container_name: imghub-prod-database
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: imghub-api
      POSTGRES_PASSWORD: aVeryStrongPassword123
      POSTGRES_DB: imghub-prod

  imghub-api:
    container_name: imghub-api
    image: imghub-api:prod
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports: 
      - "80:8080"
    depends_on:
      - imghub-prod-database
