FROM openjdk:17

#Change when app version changes
ARG executable_name="imghub-api-0.0.1-SNAPSHOT.jar"

COPY target/${executable_name} ${executable_name}

#Change when app version changes
ENTRYPOINT ["java","-jar", "imghub-api-0.0.1-SNAPSHOT.jar"]